### ISSUE TITLE
Building Docs

### ISSUE THREAD

**Issue by AntonReinhard** [lte678/JuliaHEP-Workshop#1]
To build the docs locally you should be able to just use the following commands in the shell (not julia)

First, to instantiate the dependencies for the docs building and using the developed package:
```
julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
```

Then, to actually build the docs:
```
julia --project=docs/ docs/make.jl
```

**Comment by lte678** [comment]
Fixed 698f22f796fafe1e29335b228abfbaf21b81e359.

Thanks Anton!
